export enum StatusMacro {
  EM_ANALISE_REGIONAL = 'EM_ANALISE_REGIONAL',
  EM_ANALISE_ASSESSORIA = 'EM_ANALISE_ASSESSORIA',
  DEVOLVIDO_AJUSTE = 'DEVOLVIDO_AJUSTE',
  EM_DESPACHO = 'EM_DESPACHO',
  EM_EXECUCAO = 'EM_EXECUCAO',
  ATENDIDO = 'ATENDIDO',
  PARCIALMENTE_ATENDIDO = 'PARCIALMENTE_ATENDIDO',
  NAO_ATENDIDO = 'NAO_ATENDIDO',
  CANCELADO = 'CANCELADO',
}

export enum TipoItem {
  ACAO_ATIVIDADE = 'ACAO_ATIVIDADE',
  PATROCINIO = 'PATROCINIO',
  SOLICITACAO_ITENS = 'SOLICITACAO_ITENS',
  CONVITE = 'CONVITE',
}

export enum StatusItem {
  PENDENTE = 'PENDENTE',
  EM_ANALISE = 'EM_ANALISE',
  ATENDIDO = 'ATENDIDO',
  PARCIALMENTE_ATENDIDO = 'PARCIALMENTE_ATENDIDO',
  NAO_ATENDIDO = 'NAO_ATENDIDO',
  ENCAMINHADO = 'ENCAMINHADO',
}

export enum ResultadoDevolutiva {
  ATENDIDO = 'ATENDIDO',
  PARCIALMENTE_ATENDIDO = 'PARCIALMENTE_ATENDIDO',
  NAO_ATENDIDO = 'NAO_ATENDIDO',
}

export enum AcaoTramitacao {
  CIENCIA = 'CIENCIA',
  CIENCIA_AUTOMATICA = 'CIENCIA_AUTOMATICA',
  APROVAR = 'APROVAR',
  DEVOLVER_AJUSTE = 'DEVOLVER_AJUSTE',
  RECUSAR = 'RECUSAR',
  DESPACHAR = 'DESPACHAR',
  DIRECIONAR = 'DIRECIONAR',
  DESIGNAR_COORDENADOR = 'DESIGNAR_COORDENADOR',
  ACEITAR = 'ACEITAR',
  ENCAMINHAR_OUTRA_AREA = 'ENCAMINHAR_OUTRA_AREA',
  REGISTRAR_DEVOLUTIVA = 'REGISTRAR_DEVOLUTIVA',
  REENVIAR_APOS_AJUSTE = 'REENVIAR_APOS_AJUSTE',
  EDITAR_ITEM = 'EDITAR_ITEM',
  EXCLUIR_ITEM_DO_FLUXO = 'EXCLUIR_ITEM_DO_FLUXO',
}

export enum Turno {
  MANHA = 'MANHA',
  TARDE = 'TARDE',
  NOITE = 'NOITE',
  INTEGRAL = 'INTEGRAL',
}
